spring:
  application:
    name: AUTH-SERVICE

  ldap:
    username: cn=admin,dc=example,dc=com
    password: adminPassword

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


security:
  jwt-secret: uQZ4Ywv3Pb9LnRc8KsGm2FhTjXnZr5xVp1DqAeSg8Bw3VyFm5Kd9Kj2Nn8YhRd5
  jwt-expire-ms: 250000
