server:
  port: 8080

spring:
  application:
    name: FILE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

security:
  jwt-secret: uQZ4Ywv3Pb9LnRc8KsGm2FhTjXnZr5xVp1DqAeSg8Bw3VyFm5Kd9Kj2Nn8YhRd5